const fs = require('fs');

const fixes = [
  // Prescurtari tehnice gaze
  ['Extindere conducte distributie si bransament polietilena cu prm',
   'Extindere retea gaze naturale din conducte de polietilena si bransament la imobil'],
  ['Extindere conducta si bransament cu p.r.m.- g.n.-presiune redusa',
   'Extindere retea gaze naturale presiune redusa si bransament la imobil'],
  ['Extindere conducta distributie si bransament cu prm presiune redusa',
   'Extindere retea gaze naturale presiune redusa si bransament la imobil'],
  ['Extindere cond. distributie gaze naturale,brans si post de reglare masurare presiune redus',
   'Extindere retea gaze naturale presiune redusa si bransament la imobil'],
  ['Extindere de distribuție gaze naturale presiune redusa, b și post de reglare',
   'Extindere retea gaze naturale presiune redusa si bransament la imobil'],
  ['Extindere conductă de distribuție g.n. presiune redusa, b și post de reglare/măsurare',
   'Extindere retea gaze naturale presiune redusa si post de reglare-masurare'],
  ['Modificarea traseului retelei de distributie gaze naturale, b și post de reglare masurare,',
   'Modificare traseu retea distributie gaze naturale si post de reglare-masurare'],
  ['Modificarea retelei de distributie a gazelor naturale presiune redusa',
   'Modificare retea de distributie gaze naturale presiune redusa'],
  ['Modificare si dezafectare traseu retea gaze naturale pentru realizarea unui nou obiectiv',
   'Modificare si dezafectare traseu retea gaze naturale pentru realizarea unui nou obiectiv'],
  ['Relocare conductă de distribuție a gazelor naturale, branșamente și posturi de reglare pre',
   'Relocare retea distributie gaze naturale, bransamente si posturi de reglare presiune'],
  ['Inlocuire conducte și bransamente presiune redusa str.1 decembrie 1918 (partial)',
   'Inlocuire conducte si bransamente gaze naturale presiune redusa pe Str. 1 Decembrie 1918'],

  // Trunchiate/incomplete
  ['Demolare c2 nr. cadastral 65701, demolare c3 si c5 nr. cadastral 65702 amplasare statie de',
   'Demolare constructii existente si amplasare statie de distributie carburanti'],
  ['Amenajare priza de apa si instalastii curent electric si apa pentru alimentare pivoti iri',
   'Amenajare priza de apa si instalatii electrice pentru alimentare sistem de irigatii'],
  ['Amenajare sensuri giratorii provizorii, cu elemente din plastic(balize) pe str. moldovei,',
   'Amenajare sensuri giratorii provizorii cu balize din plastic pe Str. Moldovei'],
  ['Revitalizarea municipiului pascani prin modernizarea infrastructurii educationale si a inf',
   'Revitalizare Pascani prin modernizarea infrastructurii educationale si de transport'],
  ['Demolare constructie existenta c1 si c3, constructie locuinta p + m',
   'Demolare constructii existente si construire locuinta (parter cu mansarda)'],
  ['Constr. magazin materiale de constructii, drumuri si platforme, parcaje, b la utilitati, r',
   'Construire magazin materiale de constructii cu drumuri, platforme, parcaje si racorduri'],
  ['Demolare constr. existenta c1, constr. centru social si cripta mortuara, b si r',
   'Demolare constructie existenta si construire centru social si cripta mortuara'],
  ['Modificare proiect in curs de executie autorizat cu ac nr. 68 din 14.06.2023, recompartime',
   'Modificare proiect in curs de executie - recompartimentare si amenajari interioare'],
  ['Ext. capăcității de producție a sc rompak incluzând și constr. unor hale de productie, dep',
   'Extindere capacitate de productie ROMPAK - hale de productie, depozitare si utilitati'],
  ['Demolare corp centrala existent c5, construire și echipare corp centrala termica pentru s',
   'Demolare corp centrala veche si construire centrala termica noua'],
  ['Supraetajare imobil identificat cu nr. cad. 69398-c1',
   'Supraetajare imobil cu un nivel suplimentar'],
  ['Supraetajare imobil identificat cu nr. cad. 70083-c1',
   'Supraetajare imobil cu un nivel suplimentar'],
  ['Amplasare ecran multimedia în scop publicitar în suprafata de 10mp pe terasa cladirii de p',
   'Amplasare ecran multimedia publicitar (10 mp) pe terasa unui imobil'],
  ['Lucrari de amenajare pentru functionalizarea podului existent cladire c2 (bl. md1) in cond',
   'Amenajare pod existent ca spatiu locuibil in Blocul MD1'],
  ['Lucrari de amenajare pentru functionalizarea podului existent cladire c3 (bl. md2) in cond',
   'Amenajare pod existent ca spatiu locuibil in Blocul MD2'],
  ['Construire capacitate nouă de producere energie electrică din biogaz la nivelul agrocomple',
   'Construire instalatie de producere energie electrica din biogaz la AGROCOMPLEX Pascani'],
  ['Schimbarea destinației clădirilor c1 (mănăstire sp+p+2e) și c3 (lacaș de cult grota p+m) i',
   'Schimbare destinatie cladiri - manastire si lacas de cult - in alta functiune'],
  ['Alimentare cu energie electrică a obiectivului centru dializă sc vital medical center memo',
   'Racordare electrica Centru de Dializa Vital Medical Center Pascani'],
  ['Extindere rețea electrică str. vârful dealului mun pașcani în zona locuinței d-lui hanganu',
   'Extindere retea electrica pe Str. Varful Dealului pentru alimentarea cu electricitate a unui imobil'],
  ['Restaurare fațade (finisaje exterioare și tâmplării) și refacere trotuare imobil c1 - bise',
   'Restaurare fatade si refacere trotuare la imobil - biserica'],
  ['Modificare de temă - solutie tehnică-construire capacitate noua de producere ee din biogaz',
   'Modificare solutie tehnica pentru instalatia de producere energie electrica din biogaz'],
  ['Înființare capacitate nouă de producere a energiei regenerabile pentru autoconsumul agroco',
   'Instalare capacitate de producere energie regenerabila pentru autoconsum la AGROCOMPLEX Pascani'],
  ['Instalație de utilizare privind racordarea la rețeaua electrică a obiectivului - stație de',
   'Racordare la reteaua electrica a statiei de pompare'],
  ['Construire stație telefonie mobilă orange cod ba 2126 topile, is, î, racord electric tubul',
   'Construire statie de telefonie mobila Orange si racord electric'],
  ['Construire catedrală ortodoxă\'\'pogorârea duhului sfânt\\ pașcani, b și r electrice, g.n, ap',
   'Construire Catedrala Ortodoxa Pogorarea Duhului Sfant Pascani cu instalatii electrice, gaze si apa'],
  ['Extindere retele de alimentare cu apă și retele de canalizare in municipiul pascani',
   'Extindere retele de alimentare cu apa si canalizare in municipiul Pascani'],
  ['Extindere retea de alimentare cu apă și reța de canalizaree, b de apă și racord canalizare',
   'Extindere retea de alimentare cu apa si canalizare, bransament apa si racord canalizare'],

  // Prescurtari constructii
  ['Constr. loc, i, b si r',
   'Construire locuinta individuala cu instalatii si racorduri la utilitati'],
  ['Constr. de locuinte nzeb pt tineri',
   'Construire locuinte cu consum energetic aproape zero (NZEB) pentru tineri'],
  ['Construire locuinta, i, b si r',
   'Construire locuinta individuala cu instalatii si racorduri la utilitati'],
  ['Construire locuinte colective medii p+4e cu spatii comerciale, i si r',
   'Construire bloc locuinte P+4E cu spatii comerciale la parter'],
  ['Constr. locuinte colective medii p+4e cu spatii comerciale, i si r',
   'Construire bloc locuinte P+4E cu spatii comerciale la parter'],
  ['Construire spatiu arhivă și birouri, î, b și r',
   'Construire spatiu arhiva si birouri cu instalatii si racorduri la utilitati'],
  ['Construire spălătorie auto tip self, î, b și r',
   'Construire spalatorie auto tip self-service cu instalatii si racorduri la utilitati'],
  ['Construire locuințe înșiruite, î, b și r',
   'Construire locuinte insirate cu instalatii si racorduri la utilitati'],
  ['Construire locuință p+1e, b+r',
   'Construire locuinta parter plus etaj cu racorduri la utilitati'],
  ['Construire anexă, b+r',
   'Construire anexa cu racorduri la utilitati'],
  ['Construire anexa 2 garaje- pe proprietate nr. cad 69932',
   'Construire anexa cu 2 garaje'],

  // Tipuri specifice
  ['Revovare energetica colegiul tehnic unirea, corp c3 si corp c4',
   'Renovare energetica Colegiul Tehnic Unirea, corpurile C3 si C4'],
  ['Construire biserica ortodoxa cu hramul sf mare mucenic dimitrie, beneficiar parohia sf ghe',
   'Construire biserica ortodoxa cu hramul Sfantul Mare Mucenic Dimitrie'],
  ['Amplasare firma luminoasa sediu bancar, agentia pascani',
   'Amplasare firma luminoasa sediu bancar Pascani'],
  ['Amplasare semnalistica magazin vodafone',
   'Amplasare semnalistica exterioara magazin Vodafone'],
  ['Amplasare (amenajare) modul comercial fast food',
   'Amenajare modul comercial tip fast-food'],
  ['Amenajare si montare sistem de irigatii, b si r, tr. str. stefan cel mare',
   'Amenajare si montare sistem de irigatii pe tronsonul Str. Stefan cel Mare'],
  ['Modernizare pta 15',
   'Modernizare post de transformare (PTA 15)'],
  ['Amplasare casete luminoase și autocolante allianz-țiriac',
   'Amplasare casete luminoase si autocolante publicitare Allianz-Tiriac'],
  ['Amplasare mijloace publicitare-ecrane multimedia-3 locatii',
   'Amplasare ecrane multimedia publicitare in 3 locatii'],
  ['Reabilitare termica ap. nr. 2, 3, 6, 7, 10,11, 14, 15 din bl. a5, sc. c din str stefan cel mare nr. 8 -pe intreg tronsonul de bloc- de la parter la ultimul etaj',
   'Reabilitare termica Bloc A5, Sc. C, Str. Stefan cel Mare nr. 8'],
  ['Amplificarea sistemului de tratare a neutrului in statia de transformare 110/20 kv pascani',
   'Modernizare sistem de tratare a neutrului in statia de transformare electrica 110/20 kV Pascani'],
  ['Montare stc la stalpul nr. 6, derivatia pt57 din lea 20kv pascani -siretel',
   'Montare STC pe stalpul liniei electrice aeriene 20kV Pascani-Siretel'],
  ['Reabilitare î',
   'Reabilitare imobil'],
  ['Racorarea la reteaua electrica a obiectivului baza rk panouri santier 64 statia c.f.',
   'Racordare la reteaua electrica - baza de panouri santier statia CF Pascani'],
  ['Modernizare colegiul național mihail sadoveanu pașcani (pr ne 2021-2027)',
   'Modernizare Colegiul National Mihail Sadoveanu Pascani (program national 2021-2027)'],
  ['Inlocuire ptcz cu p.t in anvelopa ptcz 38-pascani și integrare in scada',
   'Inlocuire post de transformare PTCZ 38 Pascani si integrare in sistemul de monitorizare SCADA'],
  ['Inlocuire retele distributie apa in zona i și zona ii',
   'Inlocuire retele de distributie apa in zona I si zona II'],
  ['Intarire de retea in vederea alimentarii cu energie electrica anexa exploatatie agricola',
   'Intarire retea electrica pentru alimentarea cu energie a unei anexe agricole'],
  ['Bransament electric casa tip familial 2',
   'Racordare electrica casa de tip familial nr. 2'],
  ['Modificare in curs de executie la proiectul autorizat prin a.c. nr. 95 din 31.08.2022',
   'Modificare proiect in curs de executie autorizat anterior'],
  ['Modificare in curs de executie la proiectul autorizat prin a.c. nr. 94 din 31.08.2022',
   'Modificare proiect in curs de executie autorizat anterior'],
  ['Modificare proiect aflat in curs de executie prin ac nr. 104/23.09.2022',
   'Modificare proiect in curs de executie autorizat anterior'],
  ['Modificare proiect în curs de execuție autorizat cu a.c nr. 119 din 20.09.2024',
   'Modificare proiect in curs de executie autorizat anterior'],
  ['Tarif racordare privind alimentarea cu e.e. a obiectivului - statie de pompare apa bruta',
   'Racordare electrica statie de pompare apa bruta'],
  ['Construire teren multisport liceul teoretic miron costin pașcani',
   'Construire teren multisport la Liceul Teoretic Miron Costin Pascani'],
  ['Reabilitare si eficientizare energetica \'\' gradinita cu program prelungit nr. 3\\ pascani (',
   'Reabilitare si eficientizare energetica Gradinita cu program prelungit nr. 3 Pascani'],
  ['Modernizarea și extinderea sistemului de iluminat public',
   'Modernizare si extindere sistem de iluminat public'],
];

let html = fs.readFileSync('c:/Users/Silviu/Desktop/Android App/www/index.html', 'utf8');
let count = 0;
for (const [bad, good] of fixes) {
  if (html.includes(bad)) {
    html = html.replaceAll(bad, good);
    count++;
  }
}
fs.writeFileSync('c:/Users/Silviu/Desktop/Android App/www/index.html', html, 'utf8');
console.log('Fixed:', count, 'of', fixes.length);

// Verify AC
const acStart = html.indexOf('const AC=[');
const acEnd = html.indexOf('];', acStart) + 2;
try {
  eval('var AC=' + html.slice(acStart + 'const AC='.length, acEnd));
  console.log('AC parses OK, entries:', AC.length);
} catch(e) {
  console.log('AC PARSE ERROR:', e.message);
}
